"""
Django settings for recom project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from dotenv import load_dotenv
from pathlib import Path


# ============================================================
# CAMINHO BASE DO PROJETO
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# CARREGAR VARIÁVEIS DO .ENV
# ============================================================

load_dotenv(BASE_DIR / ".env")


# ============================================================
# CONFIGURAÇÕES BÁSICAS
# ============================================================

# SECURITY WARNING:
# mantenha a secret key protegida em produção.
SECRET_KEY = "django-insecure-dlkll^@_7_u8sq1q72^vozzv_@m-9w5d6mr3d=r_olb20e7^6a"

# SECURITY WARNING:
# não utilize DEBUG=True em produção.
DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# APLICAÇÕES INSTALADAS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Apps do projeto RECOM
    "core",
    "usuarios",
    "escolas",
    "cartao_programa",
    "visitas",
    "ocorrencias",
    "acoes_educativas",
    "mediacao",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URLS
# ============================================================

ROOT_URLCONF = "recom.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates"
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "recom.wsgi.application"


# ============================================================
# BANCO DE DADOS
# POSTGRESQL
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv(
            "POSTGRES_DB"
        ),

        "USER": os.getenv(
            "POSTGRES_USER"
        ),

        "PASSWORD": os.getenv(
            "POSTGRES_PASSWORD"
        ),

        "HOST": os.getenv(
            "POSTGRES_HOST",
            "localhost"
        ),

        "PORT": os.getenv(
            "POSTGRES_PORT",
            "5433"
        ),
    }
}


# ============================================================
# VALIDAÇÃO DE SENHAS
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNACIONALIZAÇÃO
# ============================================================

LANGUAGE_CODE = "pt-br"

LANGUAGES = [
    ("pt-br", "Português do Brasil"),
    ("en", "English"),
]

TIME_ZONE = "America/Fortaleza"

USE_I18N = True

USE_TZ = True


# ============================================================
# ARQUIVOS DE TRADUÇÃO
# ============================================================

LOCALE_PATHS = [
    BASE_DIR / "locale"
]


# ============================================================
# ARQUIVOS ESTÁTICOS
# ============================================================

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ============================================================
# TIPO PADRÃO DE CHAVE PRIMÁRIA
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"