# Generated by Django 5.2.6 on 2026-07-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('conselho', models.CharField(choices=[('CRM', 'CRM'), ('COREN', 'COREN'), ('CRO', 'CRO'), ('CRF', 'CRF'), ('CRBM', 'CRBM'), ('OUTRO', 'Outro')], max_length=10)),
                ('registro', models.CharField(max_length=30)),
                ('especialidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='unidades.unidadesaude')),
            ],
        ),
    ]
