# Generated by Django 6.0.3 on 2026-09-10 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0004_escola_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RondaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField(verbose_name='Data da visita')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('tipo_visita', models.CharField(choices=[('ROTINA', 'Visita de rotina'), ('SAIDA', 'Acompanhamento de saída'), ('EVENTO', 'Acompanhamento de evento'), ('APOIO', 'Apoio / atendimento'), ('OUTRA', 'Outra')], default='ROTINA', max_length=20, verbose_name='Tipo de visita')),
                ('situacao', models.CharField(choices=[('SEM_ALTERACAO', 'Sem alteração'), ('COM_ALTERACAO', 'Com alteração')], default='SEM_ALTERACAO', max_length=20, verbose_name='Situação')),
                ('relato', models.TextField(blank=True, verbose_name='Relato da visita')),
                ('orientacoes', models.TextField(blank=True, verbose_name='Orientações / providências')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='escolas.escola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Ronda / Visita',
                'verbose_name_plural': 'Rondas / Visitas',
                'ordering': ['-data_visita', '-horario'],
            },
        ),
    ]
