# Generated by Django 6.0.3 on 2026-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rondavisita',
            name='equipe',
            field=models.CharField(choices=[('A', 'Equipe A'), ('B', 'Equipe B'), ('C', 'Equipe C'), ('D', 'Equipe D'), ('E', 'Equipe E'), ('F', 'Equipe F')], default='A', max_length=1, verbose_name='Equipe responsável'),
            preserve_default=False,
        ),
    ]
