# Generated by Django 6.0.3 on 2026-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_rondavisita_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rondavisita',
            name='equipe',
            field=models.CharField(choices=[('A', 'Equipe A'), ('B', 'Equipe B'), ('C', 'Equipe C'), ('D', 'Equipe D'), ('E', 'Equipe E'), ('F', 'Equipe F'), ('EXTRA', 'Equipe Extraordinário')], max_length=10, verbose_name='Equipe responsável'),
        ),
        migrations.AlterField(
            model_name='rondavisita',
            name='tipo_visita',
            field=models.CharField(choices=[('ROTINA', 'Visita de rotina'), ('ENTRADA', 'Acompanhamento de entrada'), ('SAIDA', 'Acompanhamento de saída'), ('EVENTO', 'Acompanhamento de evento'), ('PALESTRA', 'Palestra'), ('FANTOCHE', 'Teatro de fantoches'), ('APOIO', 'Apoio / atendimento'), ('OUTRA', 'Outra')], default='ROTINA', max_length=20, verbose_name='Tipo de visita'),
        ),
    ]
