# Generated by Django 5.2.6 on 2026-07-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
        ('unidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tipo_exame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='exames.tipoexame'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='unidades.unidadesaude'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='exames.agendamento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='unidades.profissional'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='unidades.unidadesaude'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='usuarios.usuario'),
        ),
    ]
