# Generated by Django 6.0.3 on 2026-08-11 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('polo', models.PositiveSmallIntegerField(choices=[(1, 'Polo 1'), (2, 'Polo 2'), (3, 'Polo 3'), (4, 'Polo 4'), (5, 'Polo 5'), (6, 'Polo 6'), (7, 'Polo 7'), (8, 'Polo 8'), (9, 'Polo 9')])),
                ('endereco', models.CharField(max_length=300)),
                ('monitoramento', models.BooleanField(default=False)),
                ('botao_panico', models.BooleanField(default=False)),
                ('quantidade_alunos', models.PositiveIntegerField(default=0)),
                ('quantidade_alunos_pcd', models.PositiveIntegerField(default=0)),
                ('modalidade', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inativacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inativada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas_inativadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GestorEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('funcao', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores', to='escolas.escola')),
            ],
        ),
    ]
