# Generated by Django 6.0.3 on 2026-09-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='gestor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='escola',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='GestorEscolar',
        ),
    ]
