# Generated by Django 6.0.3 on 2026-09-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_escola_gestor_escola_telefone_delete_gestorescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProblematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de problemática',
                'verbose_name_plural': 'Tipos de problemáticas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EscolaProblematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('ATIVA', 'Ativa'), ('EM_ACOMPANHAMENTO', 'Em acompanhamento'), ('RESOLVIDA', 'Resolvida')], default='ATIVA', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problematicas', to='escolas.escola')),
                ('tipo_problematica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='escolas.tipoproblematica')),
            ],
            options={
                'verbose_name': 'Problemática da escola',
                'verbose_name_plural': 'Problemáticas das escolas',
                'ordering': ['escola', 'tipo_problematica'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'tipo_problematica'), name='unique_escola_tipo_problematica')],
            },
        ),
    ]
