# Generated by Django 6.0.3 on 2026-09-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_tipoproblematica_escolaproblematica'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='bairro',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
