# Generated by Django 6.0.3 on 2026-09-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_escola_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='telefone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
